config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('service', include('service_app.urls', namespace='service_app')),
    path('customer/', include('customers_app.urls', namespace='customers_app')),
    path('log/', include('logger_app.urls', namespace='logger_app')),
    path('users/', include('users_app.urls', namespace='users_app')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logger_app/urls.py
from django.urls import path

from logger_app.apps import LoggerAppConfig
from logger_app.views import MailingLogListView, MailingLogView

app_name = LoggerAppConfig.name

urlpatterns = [
    path('mailing/', MailingLogListView.as_view(), name='log'),
    path('mailing/<int:pk>', MailingLogView.as_view(), name='mailing_log'),
]

service_app/urls.py
from django.urls import path

from service_app.apps import ServiceAppConfig
from service_app.views import MailingListView, MailingCreateView, MailingUpdateView, set_pause, \
    MailingDeleteView, start_mailing, MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    set_active

app_name = ServiceAppConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/activity/<int:pk>/', set_pause, name='pause'),
    path('mailing/send/<int:pk>/', start_mailing, name='start_mailing'),
    path('mailing/active/<int:pk>/', set_active, name='set_active'),
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
]

service_app/models.py
from datetime import timedelta

from django.db import models
from django.utils.timezone import now

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    title = models.CharField(max_length=30, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey('users_app.User', **NULLABLE, on_delete=models.CASCADE, verbose_name='создал')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    # MINUTE = 'MIN'
    # HORSE = 'H'
    # DAY = 'D'
    # WEEK = 'W'
    # MONTH = 'M'
    # YEAR = 'Y'

    MINUTE = 1
    HORSE = 60
    DAY = HORSE * 24
    WEEK = DAY * 7
    MONTH = DAY * 30
    YEAR = DAY * 365

    PERIODIC_CHOICES = [
        (MINUTE, 'Минута'),
        (HORSE, 'Час'),
        (DAY, 'День'),
        (WEEK, 'Неделя'),
        (MONTH, 'Месяц'),
        (YEAR, 'Год'),
    ]

    CREATED = 'CR'
    LAUNCHED = 'LA'
    COMPLETED = 'CP'
    PAUSED = 'PA'

    STATUS_CHOICES = [
        (CREATED, 'Создана'),
        (LAUNCHED, 'Запущена'),
        (COMPLETED, 'Завершена'),
        (PAUSED, 'Пауза'),
    ]

    name = models.CharField(max_length=25, verbose_name='название рассылки')
    message = models.ForeignKey(Message, **NULLABLE, on_delete=models.CASCADE, verbose_name='Сообщение')
    periodic = models.IntegerField(choices=PERIODIC_CHOICES, default=DAY, verbose_name='периодичность')
    start_time = models.DateTimeField(default=now, verbose_name='начало рассылки')
    stop_time = models.DateTimeField(**NULLABLE, verbose_name='окончание рассылки')
    send_time = models.DateTimeField(**NULLABLE, verbose_name='последняя отправка')
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=CREATED, verbose_name='статус')
    customers = models.ManyToManyField('customers_app.Customer', verbose_name='клиенты')
    owner = models.ForeignKey('users_app.User', **NULLABLE, on_delete=models.CASCADE, verbose_name='создал')
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.name} ({self.get_periodic_display()})'

    class Meta:
        verbose_name = 'рассылку'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('set_pause', 'Приостановка рассылки'),
            ('start_mailing', 'Ручной запуск рассылки'),
            ('set_active', 'Активировать рассылку'),
        ]

service_app/forms.py
from django import forms
from django.contrib import auth
from django.forms import CheckboxInput

from customers_app.models import Customer
from service_app.models import Mailing, Message


class StyleFrmMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFrmMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # получаем пользователя и с целью избежания ошибок, удаляем
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        # фильтруем сообщения и клиентов по пользователю если он не является персоналом
        if not self.user.is_staff:
            self.fields['message'].queryset = Message.objects.filter(owner=self.user)
            self.fields['customers'].queryset = Customer.objects.filter(owner=self.user)

    class Meta:
        model = Mailing
        fields = ['name', 'message', 'periodic', 'start_time', 'stop_time', 'customers',]


class MessageForm(StyleFrmMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = ['title', 'body',]

service_app/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from service_app.forms import MessageForm, MailingForm
from service_app.models import Mailing, Message
from service_app.services import send_mailing


class UserHasPermissionMixin:
    def has_permission(self):
        # Проверяем, является ли пользователь владельцем объекта, если да, то разрешаем операцию
        if self.model.objects.get(pk=self.kwargs.get('pk')).owner == self.request.user:
            return True
        # если не является, то следуем ограничениям прав permission_required
        return super().has_permission()


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    paginate_by = 10
    queryset = Mailing.objects.filter().order_by('pk').reverse()

    extra_context = {
        'title': 'Рассылки',
        'description': 'Список рассылок',
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        return queryset.filter(owner=self.request.user)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    paginate_by = 10
    queryset = Message.objects.filter().order_by('pk').reverse()

    extra_context = {
        'title': 'Сообщения',
        'description': 'Список сообщений',
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        return queryset.filter(owner=self.request.user)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    success_url = reverse_lazy('service_app:list')
    form_class = MailingForm
    extra_context = {
        'title': 'Рассылки',
        'description': 'Создание новой рассылки',
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Добавляем в форму аргумент содержащий текущего пользователя
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    success_url = reverse_lazy('service_app:message_list')
    form_class = MessageForm
    extra_context = {
        'title': 'Сообщение',
        'description': 'Создание нового сообщения',
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserHasPermissionMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    permission_required = 'service_app.change_mailing'
    form_class = MailingForm
    success_url = reverse_lazy('service_app:list')
    extra_context = {
        'title': 'Рассылки',
        'description': 'Изменение рассылки',
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Добавляем в форму аргумент содержащий текущего пользователя
        kwargs["user"] = self.request.user
        return kwargs


class MessageUpdateView(LoginRequiredMixin, UserHasPermissionMixin, PermissionRequiredMixin, UpdateView):
    model = Message
    permission_required = 'service_app.change_message'
    success_url = reverse_lazy('service_app:message_list')
    form_class = MessageForm
    extra_context = {
        'title': 'Сообщение',
        'description': 'Изменение сообщения',
    }


class MailingDeleteView(LoginRequiredMixin, UserHasPermissionMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    permission_required = 'service_app.delete_mailing'
    success_url = reverse_lazy('service_app:list')
    extra_context = {
        'description': 'Удаление рассылки',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = get_object_or_404(Mailing, pk=self.kwargs.get('pk'))
        return context_data


class MessageDeleteView(LoginRequiredMixin, UserHasPermissionMixin, PermissionRequiredMixin, DeleteView):
    model = Message
    permission_required = 'service_app.delete_message'
    success_url = reverse_lazy('service_app:message_list')
    extra_context = {
        'description': 'Удаление сообщения',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = get_object_or_404(Message, pk=self.kwargs.get('pk'))
        return context_data


@login_required
def set_pause(request, pk):
    item = get_object_or_404(Mailing, pk=pk)

    # Проверяем, является ли пользователь создателем рассылки
    # или есть ли у него права на постановку паузы
    # и рассылка активная
    if (item.owner == request.user or request.user.has_perms(['service_app.set_pause'])) and item.is_active:
        if item.status == Mailing.PAUSED:
            item.status = Mailing.CREATED
        else:
            item.status = Mailing.PAUSED

        item.save()

    return redirect(reverse('service_app:list'))


@login_required
def start_mailing(request, pk):
    item = get_object_or_404(Mailing, pk=pk)

    # Если пользователь создатель
    # или имеет права на отправку
    # и рассылка активная
    if (item.owner == request.user or request.user.has_perms(['service_app.set_pause'])) and item.is_active:
        send_mailing(item, manual=True)
    return redirect(reverse('service_app:list'))


@permission_required('service_app.set_active')
@login_required
def set_active(request, pk):
    item = get_object_or_404(Mailing, pk=pk)
    if item.is_active:
        item.is_active = False
        item.status = Mailing.PAUSED
    else:
        item.is_active = True
        item.status = Mailing.CREATED

    item.save()

    return redirect(reverse('service_app:list'))

service_app/templates/service_app/includes/inc_mailing_table.html
<table class="table table-secondary">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Название рассылки</th>
        <th scope="col">Периодичность</th>
        <th scope="col">Тема</th>
        <th scope="col">Начало рассылки</th>
        <th scope="col">Статус</th>
        <th scope="col">Управление</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr {% if object.is_active %}
            {% if object.status == 'PA' %}
                class="table-warning"
            {% else %}
                class="table-success"
            {% endif %}
        {% else %}
                class="table-secondary"
        {% endif %}>
            <th scope="row">{{ object.pk }}</th>
            <td>
                <p>{{ object.name|truncatechars:25 }}</p>
                {% if user.is_staff %}
                    <p>({{ object.owner }})</p>
                {% endif %}
            </td>
            <td>{{ object.get_periodic_display }}</td>
            <td>
                <a href="{% url 'service_app:message_update' object.message.pk %}">
                    {{ object.message|truncatechars:25 }}
                </a>
            </td>
            <td>{{ object.start_time }}</td>
            <td>{% if object.is_active %}
                <a href="{% url 'logger_app:mailing_log' object.pk %}">
                    {{ object.get_status_display }}
                </a>
            {% else %}
                <a class="text-danger" href="{% url 'logger_app:mailing_log' object.pk %}">
                    ОТКЛЮЧЕНО!
                </a>
            {% endif %}
            </td>
            <td>
                <div>
                    {% if perms.service_app.set_active %}
                        {% if object.is_active %}
                            <a class="btn btn-warning"
                               href="{% url 'service_app:set_active' object.pk %}">Выкл</a>
                        {% else %}
                            <a class="btn btn-success"
                               href="{% url 'service_app:set_active' object.pk %}">Вкл</a>
                        {% endif %}
                    {% endif %}
                    {% if object.owner == user or perms.service_app.start_mailing %}
                        <a class="btn btn-primary"
                           href="{% url 'service_app:start_mailing' object.pk %}">Go</a>
                    {% endif %}
                    {% if object.owner == user or perms.service_app.set_pause %}
                        {% if object.status == 'PA' %}
                            <a class="btn btn-success"
                               href="{% url 'service_app:pause' object.pk %}">Старт</a>
                        {% else %}
                            <a class="btn btn-secondary"
                               href="{% url 'service_app:pause' object.pk %}">Пауза</a>
                        {% endif %}
                    {% endif %}
                    {% if object.owner == user or perms.service_app.change_mailing %}
                        <a class="btn btn-outline-primary"
                           href="{% url 'service_app:mailing_update' object.pk %}">Изменить</a>
                    {% endif %}
                    {% if object.owner == user or perms.service_app.delete_mailing %}
                        <a class="btn btn-outline-danger"
                           href="{% url 'service_app:mailing_delete' object.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </td>
        </tr>
    {% endfor %}
</table>

service_app/templates/service_app/includes/inc_message_table.html
<table class="table table-secondary table-striped">
    <thead class="mt-5">
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Тема</th>
        <th scope="col">содержимое</th>
        <th scope="col">Управление</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr>
            <th scope="row">{{ object.pk }}</th>
            <td>{{ object.title }}</td>
            <td>{{ object.body|truncatechars:70 }}</td>
            <td>
                <a class="btn btn-outline-primary"
                   href="{% url 'service_app:message_update' object.pk %}">изменить</a>
                <a class="btn btn-outline-danger"
                   href="{% url 'service_app:message_delete' object.pk %}">удалить</a>
            </td>
        </tr>
    {% endfor %}
</table>