blog_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog_app.apps import BlogAppConfig
from blog_app.views import PostCreateView, PostEditListView, PostListView, PostUpdateView, PostDetailView, \
    PostDeleteView, published

app_name = BlogAppConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='blog'),
    path('edit_list/', PostEditListView.as_view(), name='edit_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('published/<int:pk>/', published, name='published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('service', include('service_app.urls', namespace='service_app')),
    path('customer/', include('customers_app.urls', namespace='customers_app')),
    path('log/', include('logger_app.urls', namespace='logger_app')),
    path('users/', include('users_app.urls', namespace='users_app')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logger_app/urls.py
from django.urls import path

from logger_app.apps import LoggerAppConfig
from logger_app.views import MailingLogListView, MailingLogView

app_name = LoggerAppConfig.name

urlpatterns = [
    path('mailing/', MailingLogListView.as_view(), name='log'),
    path('mailing/<int:pk>', MailingLogView.as_view(), name='mailing_log'),
]

main_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main_app.apps import MainAppConfig
from main_app.views import IndexView, ContactView

app_name = MainAppConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
]

users_app/urls.py
from django.urls import path

from users_app.apps import UsersAppConfig
from users_app.views import (LoginView, LogoutView, RegisterView, EmailVerifyView, PasswordRecoveryView, \
                             UpdateProfileView, UserListView, set_active, UserDetailView)

app_name = UsersAppConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_verify/', EmailVerifyView.as_view(), name='email_verify'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery'),
    path('user/list', UserListView.as_view(), name='list'),
    path('user/profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('user/active/<int:pk>/', set_active, name='set_active'),
]

blog_app/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    owner = models.ForeignKey('users_app.User', **NULLABLE, on_delete=models.SET_NULL, verbose_name='Создатель')
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(**NULLABLE, max_length=150, verbose_name='slug')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(**NULLABLE, verbose_name='превью')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.created_at} {self.title}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        permissions = [
            ('manage_content', 'Контент менеджмент'),
        ]

main_app/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Contact(models.Model):
    country = models.CharField(max_length=50, verbose_name='Страна')
    inn = models.CharField(max_length=13, verbose_name='ИНН')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    phone = models.CharField(max_length=50, verbose_name='Телефон')

    def __str__(self):
        return f'{self.address}'

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'


class Message(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    phone = models.CharField(**NULLABLE, max_length=20, verbose_name='Телефон')
    email = models.CharField(**NULLABLE, max_length=100, verbose_name='email')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name} {self.phone} {self.email}'

    class Meta:
        verbose_name = 'Сообщения'
        verbose_name_plural = 'Сообщение'

main_app/views.py
from django.core.cache import cache
from django.utils.timezone import now
from django.views.generic import TemplateView

from blog_app.models import Post
from config import settings
from customers_app.models import Customer
from main_app.models import Contact, Message
from main_app.utils import get_random_list
from service_app.models import Mailing
from users_app.models import User


class IndexView(TemplateView):
    template_name = 'main_app/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        if settings.CACHE_ENABLED:
            # Если кэширование включено, но идем в redis за нашими запросами
            user_count = cache.get('user_count')
            if user_count is None:
                user_count = User.objects.count()
                cache.set('user_count', user_count)

            mailing_count = cache.get('mailing_count')
            if mailing_count is None:
                mailing_count = Mailing.objects.count()
                cache.set('mailing_count', mailing_count)

            mailing_active_count = cache.get('mailing_active_count')
            if mailing_active_count is None:
                mailing_active_count = (Mailing.objects.
                                        filter(start_time__lte=now()).
                                        exclude(status=Mailing.PAUSED).
                                        exclude(status=Mailing.COMPLETED).
                                        exclude(is_active=False).count())
                cache.set('mailing_active_count', mailing_active_count)

            customers_all = cache.get('customers_all')
            if customers_all is None:
                customers_all = Customer.objects.all()
                cache.set('customers_all', customers_all)

            post_list = cache.get('post_list')
            if post_list is None:
                post_list = get_random_list(Post)
                cache.set('post_list', post_list)

        else:
            # Если кэширование выключено, идем сразу в базу данных
            user_count = User.objects.count()
            mailing_count = Mailing.objects.count()
            mailing_active_count = (Mailing.objects.
                                    filter(start_time__lte=now()).
                                    exclude(status=Mailing.PAUSED).
                                    exclude(status=Mailing.COMPLETED).
                                    exclude(is_active=False).count())
            customers_all = Customer.objects.all()
            post_list = get_random_list(Post)

        # Количество пользователей сервиса
        context_data['user_count'] = user_count

        # Количество рассылок всего
        context_data['mailing_count'] = mailing_count

        # Количество активных рассылок
        context_data['mailing_active_count'] = mailing_active_count

        # Количество уникальных клиентов для рассылок
        customers = set(map(str, customers_all))
        context_data['customer_count'] = len(customers)

        # 3 случайных записи из блога
        context_data['post_list'] = post_list

        return context_data


class ContactView(TemplateView):
    template_name = 'main_app/contact_view.html'
    extra_context = {
        'title': 'Контакты',
        'description': 'Наши адреса',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            contact_all = cache.get('contact_all')
            if contact_all is None:
                contact_all = Contact.objects.all()
                cache.set('contact_all', contact_all)

        context_data['object_list'] = Contact.objects.all()
        return context_data

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        name = self.request.POST.get('name')
        phone = self.request.POST.get('phone')
        email = self.request.POST.get('email')
        message = self.request.POST.get('message')
        Message.objects.create(name=name, phone=phone, email=email, message=message)
        return self.render_to_response(context)

main_app/templates/main_app/base.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<nav>
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                {% include 'main_app/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'main_app:index' %}" class="navbar-brand d-flex align-items-center">
                <img src="{% static 'img/home_logo.svg' %}" alt="Logo" width="50" height="50"
                     class="d-inline-block align-text-top">
                <strong>HomeSys</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row col-6 mt-3">
        <h3>{{ description }}</h3>
    </div>
</div>
<div class="container mt-5">

    {% block content %}
    {% endblock %}

</div>
<footer class="container pt-4 my-md-5 pt-md-5 border-top">
    <div class="row m-lg-1">
        <div class="col-6 col-md">
            HomeSys &copy; 2023
        </div>
        <div class="col-6 col-md">
            <h5>Навигация</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'service_app:list' %}">Рассылки</a></li>
                <li><a class="text-muted" href="{% url 'customers_app:list' %}">Клиенты</a></li>
                <li><a class="text-muted" href="{% url 'logger_app:log' %}">Логи</a></li>
                <li><a class="text-muted" href="{% url 'blog_app:blog' %}">Блог</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Мы в соцсетях</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Вконтакте</a></li>
                <li><a class="text-muted" href="#">Телеграмм</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'main_app:contact' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main_app/templates/main_app/contact_view.html
{% extends 'main_app/base.html' %}
{% block content %}
    <div class="row">
        {% for contact in object_list %}
            <div class="col-9">
                <div class="row">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <td class="w-25">Страна</td>
                                    <td>{{ contact.country }}</td>
                                </tr>
                                <tr>
                                    <td class="w-25">ИНН</td>
                                    <td>{{ contact.inn }}</td>
                                </tr>
                                <tr>
                                    <td class="w-25">Адрес</td>
                                    <td>{{ contact.address }}</td>
                                </tr>
                                <tr>
                                    <td class="w-25">Телефон</td>
                                    <td>{{ contact.phone }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h5><b>Свяжитесь с нами</b></h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон">
                        </div>
                        <div class="mb-3">
                            <input type="email" name="email" class="form-control" id="email"
                                   placeholder="email">
                        </div>
                        <div class="mb-3">
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}

{% load users_tags %}
{% block content %}

    <section class="py-5 container">
        <div class="row py-lg-5">
            <div class="col-lg-8 col-md-8 mx-auto">
                <h1 class="fw-light text-center">Сервис рассылок HomeSys</h1>
                <p class="lead text-body-secondary">Удобный сервис для вашего бизнеса.
                    Вы никогда не забудете поздравить клиентов с праздниками, напомнить
                    о проходящих акциях, новых поступлениях и т.д.
                    Клиенты всегда будут вкурсе Ваших событий. </p>
                <table class="table">
                    <tr>
                        <td>Зарегистрированных пользователей</td>
                        <td>{{ user_count }}</td>
                    </tr>
                    <tr>
                        <td>Рассылок всего</td>
                        <td>{{ mailing_count }}</td>
                    </tr>
                    <tr>
                        <td>Активных рассылок</td>
                        <td>{{ mailing_active_count }}</td>
                    </tr>
                    <tr>
                        <td>Уникальных клиентов для рассылок</td>
                        <td>{{ customer_count }}</td>
                    </tr>
                </table>
                <p class="text-center">
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users_app:register' %}" class="btn btn-primary my-2">Зарегистрироваться</a>
                        <a href="{% url 'users_app:login' %}" class="btn btn-secondary my-2">Войти</a>
                    {% else %}
                        <a href="{% url 'service_app:list' %}" class="btn btn-primary my-2">Рассылки</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </section>

    <a class="text-center" href="{% url 'blog_app:blog' %}">
        <h3><i>Смотреть все записи блога</i></h3>
    </a>
    <div class="row mt-4">
        {% for post in post_list %}
            <div class="col-4">
                <div class="card shadow">
                    <div style="height: 300px;">
                        <a class="p-1 h-auto d-inline-block" href="{% url 'blog_app:post' post.pk %}">
                            <img class="card-img-top"
                                 src="{{ post.image|mediapath }}"
                                 alt="Card image cap">
                        </a>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><b>{{ post.title|truncatechars:29 }}</b></p>
                        <p>{{ post.body|truncatechars:85 }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}