blog_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog_app.apps import BlogAppConfig
from blog_app.views import PostCreateView, PostEditListView, PostListView, PostUpdateView, PostDetailView, \
    PostDeleteView, published

app_name = BlogAppConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='blog'),
    path('edit_list/', PostEditListView.as_view(), name='edit_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('published/<int:pk>/', published, name='published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('service', include('service_app.urls', namespace='service_app')),
    path('customer/', include('customers_app.urls', namespace='customers_app')),
    path('log/', include('logger_app.urls', namespace='logger_app')),
    path('users/', include('users_app.urls', namespace='users_app')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    owner = models.ForeignKey('users_app.User', **NULLABLE, on_delete=models.SET_NULL, verbose_name='Создатель')
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(**NULLABLE, max_length=150, verbose_name='slug')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(**NULLABLE, verbose_name='превью')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.created_at} {self.title}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        permissions = [
            ('manage_content', 'Контент менеджмент'),
        ]

blog_app/forms.py
from django import forms

from blog_app.models import Post
from service_app.forms import StyleFrmMixin


class PostForm(StyleFrmMixin, forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body', 'image', 'is_published']

blog_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify

from blog_app.forms import PostForm
from blog_app.models import Post


class PostListView(ListView):
    model = Post
    paginate_by = 5
    queryset = Post.objects.filter().order_by('pk').reverse()
    extra_context = {
        'title': 'Блог',
        'description': 'Наши события'
    }


class PostEditListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10
    queryset = Post.objects.filter().order_by('pk')
    template_name = 'blog_app/post_edit_list.html'
    extra_context = {
        'title': 'Управление',
        'description': 'Настройка ленты'
    }


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.objects = super().get_object(queryset)
        self.objects.views_count += 1
        self.objects.save()
        return self.objects

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        post_item = Post.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = post_item.slug
        context_data['description'] = post_item.title

        return context_data


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    permission_required = 'blog_app.add_post'
    form_class = PostForm
    extra_context = {
        'title': 'Новая запись',
        'description': 'Создание новой записи в блог'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.owner = self.request.user
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        # return reverse('blog_app:blog_app', args=[self.object.pk])
        return reverse('blog_app:edit_list')


class PostUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Post
    permission_required = 'blog_app.change_post'
    form_class = PostForm
    extra_context = {
        'title': 'Новая запись',
        'description': 'Создание новой записи в блог'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog_app:post', args=[self.object.pk])


class PostDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Post
    permission_required = 'blog_app.delete_post'
    extra_context = {
        'title': 'Удаление',
        'description': 'Удаление записи',
    }

    def get_success_url(self):
        return reverse('blog_app:blog')


def published(request, pk):
    post_item = get_object_or_404(Post, pk=pk)
    if post_item.is_published:
        post_item.is_published = False
    else:
        post_item.is_published = True

    post_item.save()

    return redirect(reverse('blog_app:edit_list'))

blog_app/templates/blog_app/post_confirm_delete.html
{% extends 'main_app/base.html' %}
{% block content %}
    <div class="row">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Действительно хотите удалить запись "{{ object.title|truncatechars:30 }}"?</p>
            <button type="submit" class="btn btn-danger">
                Удалить
            </button>
            <input type="button" class="btn btn-secondary" onclick="history.back()" value="Отмена"/>
        </form>
    </div>
{% endblock %}

blog_app/templates/blog_app/post_detail.html
{% extends 'main_app/base.html' %}
{% load users_tags %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="mt-0">
                <p class="card-text mb-auto">{{ object.body }}</p>
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="mt-5">
                        <input type="button" class="btn btn-outline-secondary form-control" onclick="history.back()"
                               value="<< назад"/>
                    </div>
                </div>
            </div>
            <div class="mt-5">
                <p class="card-text mb-auto">Добавлено: {{ object.created_at }}</p>
                <p class="card-text mb-auto">Пользователем {{ object.owner }}</p>
            </div>
            <div class="mt-3">
                <p class="card-text mb-auto">Количество просмотров: {{ object.views_count }}</p>
            </div>
            <div class="mt-5">
                {% if perms.blog_app.change_post %}
                    <a type="button" class="btn btn-outline-primary"
                       href="{% url 'blog_app:update' object.pk %}">Изменить</a>
                {% endif %}
                {% if perms.blog_app.delete_post %}
                    <a type="button" class="btn btn-outline-danger"
                       href="{% url 'blog_app:delete' object.pk %}">удалить</a>
                {% endif %}
            </div>
        </div>
        <div class="col-6">
            <img class="card-img-top"
                 src="{{ object.image|mediapath }}"
                 alt="Card image cap">
        </div>
    </div>
{% endblock %}

blog_app/templates/blog_app/post_edit_list.html
{% extends 'main_app/base.html' %}
{% block content %}
    <div class="col-6 mb-5">
        <a class="btn btn-outline-secondary"
           href="{% url 'blog_app:blog' %}"><< назад</a>
        <a class="btn btn-outline-primary"
           href="{% url "blog_app:create" %}">Добавить запись</a>
    </div>
    <div class="row">
        {% include 'blog_app/includes/inc_post_table.html' %}
    </div>
        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class='btn btn-outline-secondary'
               href="?page=1">&laquo; Первая</a>
            <a class='btn btn-outline-secondary'
               href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class='btn btn-outline-secondary'
               href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a class='btn btn-outline-secondary'
               href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}

blog_app/templates/blog_app/post_form.html
{% extends 'main_app/base.html' %}
{% block content %}
    <div class="row">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                    Изменить
                {% else %}
                    Создать
                {% endif %}
            </button>
            <input type="button" class="btn btn-secondary" onclick="history.back()" value="Отмена"/>
        </form>
    </div>
{% endblock %}

blog_app/templates/blog_app/post_list.html
{% extends 'main_app/base.html' %}
{% load cache %}
{% block content %}
    {% if perms.blog_app.manage_content %}
        <div class="col-auto mb-5">
            <a href="{% url "blog_app:edit_list" %}" class="btn btn-outline-primary">Настроить ленту</a>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12">
            {% for object in object_list %}
                {% if object.is_published %}
                    {% include 'blog_app/includes/inc_post_card.html' %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class='btn btn-outline-secondary'
               href="?page=1">&laquo; Первая</a>
            <a class='btn btn-outline-secondary'
               href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class='btn btn-outline-secondary'
               href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a class='btn btn-outline-secondary'
               href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}