config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('service', include('service_app.urls', namespace='service_app')),
    path('customer/', include('customers_app.urls', namespace='customers_app')),
    path('log/', include('logger_app.urls', namespace='logger_app')),
    path('users/', include('users_app.urls', namespace='users_app')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
from django.urls import path

from users_app.apps import UsersAppConfig
from users_app.views import (LoginView, LogoutView, RegisterView, EmailVerifyView, PasswordRecoveryView, \
                             UpdateProfileView, UserListView, set_active, UserDetailView)

app_name = UsersAppConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_verify/', EmailVerifyView.as_view(), name='email_verify'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery'),
    path('user/list', UserListView.as_view(), name='list'),
    path('user/profile/<int:pk>/', UserDetailView.as_view(), name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('user/active/<int:pk>/', set_active, name='set_active'),
]

users_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}

COUNTRY_CHOICES = {
    ('RU', 'Россия'),
    ('AM', 'Армения'),
    ('BY', 'Беларусь'),
    ('GE', 'Грузия'),
    ('KZ', 'Казахстан'),
    ('KG', 'Киргизия'),
    ('LV', 'Латвия'),
    ('LT', 'Литва'),
    ('MD', 'Молдова'),
    ('CK', 'Острова Кука'),
    ('UZ', 'Узбекистан'),
    ('OS', 'Южная Осетия'),
    ('XX', 'Другая страна'),
}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    first_name = models.CharField(**NULLABLE, max_length=35, verbose_name='Имя')
    last_name = models.CharField(**NULLABLE, max_length=35, verbose_name='Фамилия')
    surname = models.CharField(**NULLABLE, max_length=35, verbose_name='Отчество')
    phone = models.CharField(**NULLABLE, max_length=35, verbose_name='Номер телефона')
    telegram = models.CharField(**NULLABLE, max_length=30, verbose_name='Telegram')
    country = models.CharField(**NULLABLE, max_length=25, choices=COUNTRY_CHOICES, verbose_name='Страна')
    avatar = models.ImageField(**NULLABLE, verbose_name='Аватар')
    key = models.CharField(**NULLABLE, max_length=25, unique=True, verbose_name='Ключ пользователя')
    is_active = models.BooleanField(default=False, verbose_name='Активен')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('set_active', 'Блокировка пользователя>'),
        ]

users_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from service_app.forms import StyleFrmMixin
from users_app.models import User


class LoginForm(StyleFrmMixin, AuthenticationForm):
    pass


class RegisterForm(StyleFrmMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(StyleFrmMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'last_name', 'first_name', 'surname', 'phone', 'telegram', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users_app/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, UpdateView, ListView, DetailView

import users_app
from users_app.forms import LoginForm, RegisterForm, UserProfileForm
from users_app.models import User
from users_app.utils import get_user_key, get_password


class LoginView(BaseLoginView):
    template_name = 'users_app/login.html'
    form_class = LoginForm


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users_app/register.html'
    success_url = reverse_lazy('users_app:email_verify')

    def form_valid(self, form):
        key = get_user_key()
        self.object = form.save()
        self.object.key = key
        self.object.save()
        send_mail(
            subject='подтверждение регистрации',
            message=f'Для подтверждения регистрации перейдите по ссылке: '
                    f'http://127.0.0.1:8000/users/email_verify/?key={key}',
            from_email=None,
            recipient_list=[self.object.email],
        )
        return super().form_valid(form)


class EmailVerifyView(TemplateView):
    template_name = 'users_app/user_verification.html'
    extra_context = {
        'title': 'Подтверждение регистрации',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        key = self.request.GET.get('key')

        # Если в запросе есть 'key', то выполняем верификацию
        if key:
            try:
                user = User.objects.get(key=key)
            except users_app.models.User.DoesNotExist:
                context['description'] = 'Пользователь не существует'
            else:
                user.is_active = True
                user.save()
                context['description'] = 'Спасибо за успешную регистрацию!'
                context['verify'] = True
            finally:
                return context

        # Если нет ключа, то предложим пользователю заглянуть в свою почту
        context['description'] = 'Для подтверждения регистрации перейдите по ссылке отправленной на Ваш email'
        context['register_end'] = True
        return context


class PasswordRecoveryView(TemplateView):
    template_name = 'users_app/reset_password.html'
    extra_context = {
        'title': 'Восстановление пароля',
    }

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        email = self.request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except users_app.models.User.DoesNotExist:
            context['description'] = 'Неверный email. Попробуйте еще раз'
        else:
            password = get_password()
            user.set_password(password)
            user.save()
            send_mail(
                subject='Восстановление пароля',
                message=f'Ваш новый пароль: {password}',
                from_email=None,
                recipient_list=[email],
            )

            return redirect(reverse('users_app:login'))
        return self.render_to_response(context)


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    paginate_by = 10
    queryset = model.objects.filter().order_by('pk').reverse()
    permission_required = 'users_app.view_user'
    extra_context = {
        'title': 'Пользователи',
        'description': 'Список пользователей',
    }


class UserDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = User
    permission_required = 'users_app.view_user'
    extra_context = {
        'title': 'Профиль',
        'description': 'Профиль пользователя',
    }

    def has_permission(self):
        # Проверяем, является ли пользователь владельцем рассылки, если да, то разрешаем операцию
        if self.model.objects.get(pk=self.kwargs.get('pk')) == self.request.user:
            return True
        # print(User.objects.get(pk=1))
        # если не является, то следуем ограничениям прав permission_required
        return super().has_permission()

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data()
        contex_data['self_user'] = self.request.user
        return contex_data


class UpdateProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    extra_context = {
        'title': 'Профиль',
        'description': 'Редактировать профиль пользователя',
    }

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('users_app:profile', args=[self.request.user.pk])


@permission_required('users_app.set_active')
@login_required
def set_active(request, pk):
    item = get_object_or_404(User, pk=pk)

    # Суперпользователя может заблокировать или разблокировать только суперпользователь
    if not item.is_superuser or request.user.is_superuser:
        if item.is_active:
            item.is_active = False
        else:
            item.is_active = True

        item.save()

    return redirect(reverse('users_app:list'))

users_app/templates/users_app/includes/inc_user_table.html
<table class="table table-secondary table-striped">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Email</th>
        <th scope="col">Имя</th>
        <th scope="col">Суперпользователь</th>
        <th scope="col">Персонал</th>
        <th scope="col">Группы</th>
        <th scope="col">Управление</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr{% if object.is_active %}
            class="table-secondary"
        {% else %}
            class="table-danger"
        {% endif %}>
            <th scope="row">{{ object.pk }}</th>
            <td>
                <a href="{% url 'users_app:profile' object.pk %}">
                    {{ object.email }}
                </a>
            </td>
            <td>
                {% if object.last_name %}
                    {{ object.last_name }}
                {% endif %}
                {% if object.first_name %}
                    {{ object.first_name }}
                {% endif %}
                {% if object.surname %}
                    {{ object.surname }}
                {% endif %}
            </td>
            <td>
                {% if object.is_superuser %}
                    Ok
                {% endif %}
            </td>
            <td>
                {% if object.is_staff %}
                    Ok
                {% endif %}
            </td>
            <td>
                {% for group in object.groups.all %}
                    <p>{{ group }}</p>
                {% endfor %}
            </td>
            <td>
                {% if perms.users_app.set_active and not object.is_superuser or user.is_superuser %}
                    {% if object.is_active %}
                        <a class="btn btn-warning"
                           href="{% url 'users_app:set_active' object.pk %}">Заблокировать</a>
                    {% else %}
                        <a class="btn btn-success"
                           href="{% url 'users_app:set_active' object.pk %}">Разблокировать</a>
                    {% endif %}
                {% endif %}
                {% if perms.users_app.change_user %}
                    <a class="btn btn-outline-primary"
                       href="#">Изменить</a>
                {% endif %}
                {% if perms.users_app.delete_user %}
                    <a class="btn btn-outline-danger"
                       href="#">Удалить</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>